---
- name: Start Elasticsearch
  docker_container:
    name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:5.5.2
    network_mode: host
    ulimits:
      - "nofile:131071:131071"
      - "memlock:-1:-1"
    env:
      xpack.security.enabled: "false"
